version: "3.8"

networks:
  backend-network:


services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      - database
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - backend-network

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - backend-network

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - backend-network
