FROM tensorflow/tensorflow:2.12.0

RUN pip install fastapi
RUN pip install uvicorn
RUN pip install psycopg2-binary
RUN pip install sqlmodel

# WebRTC library for Python
RUN pip install aiortc

# KI
# RUN apt-get update && apt-get install libgl1
# RUN pip install opencv-python
RUN pip install opencv-python-headless
RUN pip install dlib

# multiprocess extends multiprocessing to provide enhanced serialization, using dill
RUN pip install dill
RUN pip install msgpack-numpy

WORKDIR /app

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
